name: saloony
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.0
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  http: ^1.0.0
  font_awesome_icon_class: ^0.0.6
  flutter_map: ^6.0.0
  permission_handler: ^11.4.0
  latlong2: ^0.9.0
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  # Exemple de fonts (optionnel)

